- hosts: apache
  vars_files:
    - vars/group_vars/apache.yml

  roles:
    - { role: geerlingguy.apache }

  tasks:
    - name: "Copy HW solutions to web dir"
      copy:
        src: /etc/ansible/hw2_playbook/files/run.sh
        dest: /var/www/html/hw2.txt
        mode: 0644
