apache_remove_default_vhost: true

apache_vhosts:
  # Additional optional properties: 'serveradmin, serveralias, extra_parameters'.
  - servername: "{{ ansible_fqdn }}"
    documentroot: "/var/www/html"
